name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3

      - name: Install libspf2
        run: |
          sudo apt-get update
          sudo apt-get install -y libspf2-dev pkg-config

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: nimble install -Y
      - name: Build with libspf2 flags
        shell: bash
        run: |
          CFLAGS="$(pkg-config --cflags libspf2)"
          LIBS="$(pkg-config --libs libspf2)"
          nim c --passC:"$CFLAGS" --passL:"$LIBS" src/spf.nim

      - name: Test with libspf2 flags
        shell: bash
        run: |
          CFLAGS="$(pkg-config --cflags libspf2)"
          LIBS="$(pkg-config --libs libspf2)"
          nimble test --passC:"$CFLAGS" --passL:"$LIBS"
