name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3

      - name: Build and install libspf2 from source
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential autoconf automake libtool
          git clone --depth=1 https://github.com/shevek/libspf2.git
          cd libspf2
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: nimble install -Y
      - run: nim c -r src/spf.nim
      - run: nimble test
