name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3

      - name: Install libspf2
        run: |
          sudo apt-get update
          sudo apt-get install -y libspf2-dev pkg-config

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: nimble install -Y
      - run: |
          nim c --passC:"-I/usr/include/spf2 -I/usr/include" --passL:"-L/usr/lib/x86_64-linux-gnu -lspf2" src/spf.nim
      - run: nimble test
